# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - freeberg-container-site

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1
      with:
        registry: index.docker.io
        username: ${{ secrets.AzureAppService_ContainerUsername_15e3416340d740e89ea8c9c2804402de }}
        password: ${{ secrets.AzureAppService_ContainerPassword_69ac9170eaf94416a4cddfd22a8c9431 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2.2.1
      with:
        push: true
        tags: my-spring-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'freeberg-container-site'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0a627da12e22427db61d3ffb2b33741b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_15e3416340d740e89ea8c9c2804402de }}/my-spring-app:${{ github.sha }}'
