# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - freeberg-java-8-workflow-change

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:                                  # Rename this, used to be "build-and-deploy"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload artifact for deployment job        # Upload the deployment artifacts
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'  # Upload whatever used to be specified in the "package" param of the deployment step

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'                    # In the template this will be the slot name parameter
      url: ${{ steps.deploy-to-webapp.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: .

    - name: Display structure of downloaded files
      run: ls -R

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'freeberg-java-8-workflow-change'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3c2cec5b96b54c23836654a1b951fd54 }}
        package: '*.jar'