
name: Publish JAR to Storage Account, and trigger webapp to pull it

on:
  push:
    branches: [ master ]

env:
  GROUP: freebergDemo
  ACCOUNT: xzopublishingaccount
  CONTAINER: deploymentContainer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: target/app.jar
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage account create   -n $ACCOUNT -g $GROUP -l westus --sku Standard_LRS
            az storage container create -n $CONTAINER --account-name $ACCOUNT
            az storage blob upload      -f app.zip --account-name $ACCOUNT -c $CONTAINER -n $ACCOUNT
            az storage blob url         --account-name $ACCOUNT -c $CONTAINER -n $ACCOUNT
            //curl -X PUT -u <user> https://{sitename}.scm.azurewebsites.net/api/zipdeploy -H "Content-Type: application/json" -d "{'packageUri':'<zipUrl>'}"
            
            az storage account delete   -y -n freebergdeployment -g $GROUP
